
# NumPy Array Creation

In this notebook, we will cover:
- Creating NumPy Arrays
- From Python Lists & Tuples
- Using Built-in NumPy Functions
- Arrays Filled with Zeros/Ones
- Identity & Diagonal Matrices
- Using `arange()` and `linspace()`
- Random Number Arrays
- Understanding Data Types (`dtype`)

---



## Creating Arrays

NumPy arrays can be created in multiple ways:
1. From Python sequences (lists, tuples)
2. Using special NumPy functions
3. Using random number generators

---



## 1. Creating Arrays from Python Lists and Tuples

We can create arrays directly from existing Python data structures.


In [3]:
import numpy as np

# From list
arr1 = np.array([1, 2, 3, 4, 5])
print("Array from list:", arr1)

# From tuple
arr2 = np.array((10, 20, 30))
print("Array from tuple:", arr2)

# 2D array (list of lists)
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:\n", arr3)


Array from list: [1 2 3 4 5]
Array from tuple: [10 20 30]
2D array:
 [[1 2 3]
 [4 5 6]]


🔹 **Note**: Unlike Python lists, NumPy arrays store **elements of the same type** for efficiency.

---



## 2. Arrays Filled with Zeros and Ones

Sometimes, we need arrays filled with default values.


In [4]:
# Array of zeros
zeros = np.zeros((3, 4))
print("Zeros array:\n", zeros)

# Array of ones
ones = np.ones((2, 5))
print("Ones array:\n", ones)

Zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


🔹 Useful for initializing weights in Machine Learning or creating placeholders.

---



## 3. Identity and Diagonal Matrices

Identity matrices are important in **linear algebra**.


In [5]:
# Identity matrix (square)
I = np.eye(4)
print("Identity matrix:\n", I)

# Diagonal matrix
D = np.diag([1, 2, 3, 4])
print("Diagonal matrix:\n", D)


Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Diagonal matrix:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]




---



## 4. Using `arange()`

`np.arange(start, stop, step)` works like Python’s `range()` but returns an array.


In [6]:
arr = np.arange(0, 10, 2)
print("Arange array:", arr)


Arange array: [0 2 4 6 8]



---

## 5. Using `linspace()`

`np.linspace(start, stop, num)` creates evenly spaced numbers between a range.


In [7]:
arr = np.linspace(0, 1, 5)
print("Linspace array:", arr)

Linspace array: [0.   0.25 0.5  0.75 1.  ]


🔹 Good for **graphing and simulations**, where precise intervals are needed.

---


## 6. Random Number Arrays

NumPy provides random number generators.


In [8]:
# Random floats between 0 and 1
rand_arr = np.random.rand(3, 3)
print("Random array:\n", rand_arr)

# Random integers
rand_int = np.random.randint(1, 100, (4, 4))
print("Random integers:\n", rand_int)

# Normal distribution (mean=0, std=1)
normal_arr = np.random.randn(5)
print("Normal distribution:", normal_arr)


Random array:
 [[0.91706564 0.87748068 0.12115631]
 [0.62111389 0.26607922 0.42234711]
 [0.16600834 0.67783561 0.79634375]]
Random integers:
 [[93 52 33 15]
 [30 83 57 34]
 [18 10 50 99]
 [59 49 98 63]]
Normal distribution: [ 0.22155911  0.01202439  1.48350826  0.1157073  -0.23774364]



---


## 7. Specifying Data Type (`dtype`)

We can control the **data type** of arrays.


In [9]:
# Integer array
arr_int = np.array([1, 2, 3], dtype=np.int32)
print("Integer array:", arr_int, "| dtype:", arr_int.dtype)

# Float array
arr_float = np.array([1, 2, 3], dtype=np.float64)
print("Float array:", arr_float, "| dtype:", arr_float.dtype)


Integer array: [1 2 3] | dtype: int32
Float array: [1. 2. 3.] | dtype: float64


🔹 Choosing correct `dtype` is important for **performance** and **memory optimization**.

---



## Summary

* Arrays can be created from lists/tuples or with NumPy functions.
* Special arrays: `zeros`, `ones`, `eye`, `diag`.
* Ranges: `arange()` and `linspace()`.
* Random arrays: `rand()`, `randint()`, `randn()`.
* Data type (`dtype`) control improves efficiency.

➡️ Next: We will explore **Array Attributes and Indexing** in NumPy.


---
