# Array Attributes and Indexing in NumPy 
**03-array-attributes-and-indexing.ipynb**

In this notebook, we will cover:

* Array Attributes
* Dimensions and Shape
* Data Types
* Size and Memory Usage
* Indexing and Slicing
* Negative Indexing
* Multi-dimensional Indexing
* Fancy Indexing
* Boolean Indexing
* Practical Examples
* Exercises

---



## Array Attributes

Every NumPy array has important attributes that give information about its structure.


In [1]:
import numpy as np

# Create a sample array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)     # rows x columns
print("Dimensions:", arr.ndim) # number of dimensions
print("Size:", arr.size)       # total number of elements
print("Data Type:", arr.dtype) # data type of elements
print("Item Size:", arr.itemsize, "bytes")  # size of each element
print("Total Memory:", arr.nbytes, "bytes") # total memory


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2
Size: 6
Data Type: int64
Item Size: 8 bytes
Total Memory: 48 bytes



---



## Dimensions and Shape

* **ndim** → Number of dimensions (axes) of the array.
* **shape** → Tuple representing size of each dimension.


In [2]:
# 1D Array
arr1 = np.array([1, 2, 3, 4])
print("1D Shape:", arr1.shape)
print("1D Dimensions:", arr1.ndim)

# 2D Array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Shape:", arr2.shape)
print("2D Dimensions:", arr2.ndim)

# 3D Array
arr3 = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print("3D Shape:", arr3.shape)
print("3D Dimensions:", arr3.ndim)


1D Shape: (4,)
1D Dimensions: 1
2D Shape: (2, 3)
2D Dimensions: 2
3D Shape: (2, 2, 2)
3D Dimensions: 3



---



## Indexing and Slicing

NumPy arrays support similar indexing/slicing as Python lists, but extended for multiple dimensions.


In [3]:
arr = np.array([10, 20, 30, 40, 50])

# Accessing elements
print(arr[0])   # First element
print(arr[-1])  # Last element

# Slicing
print(arr[1:4])  # Elements from index 1 to 3
print(arr[:3])   # First three elements
print(arr[2:])   # From index 2 to end


10
50
[20 30 40]
[10 20 30]
[30 40 50]



---



## Negative Indexing

Just like Python lists, you can use negative indices to count from the end.


In [4]:
arr = np.array([100, 200, 300, 400, 500])

print("Last element:", arr[-1])
print("Second last element:", arr[-2])
print("Slice last 3 elements:", arr[-3:])


Last element: 500
Second last element: 400
Slice last 3 elements: [300 400 500]



---


## Multi-dimensional Indexing

You can access elements in **2D** or higher-dimensional arrays using row/column indices.


In [5]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

print(arr2d[0, 0])  # First row, first column
print(arr2d[1, 2])  # Second row, third column

# Slicing in 2D
print(arr2d[:, 1])   # All rows, second column
print(arr2d[0, :])   # First row, all columns


1
6
[2 5]
[1 2 3]



---


## Fancy Indexing

Fancy indexing allows selecting elements using arrays/lists of indices.


In [6]:
arr = np.array([10, 20, 30, 40, 50])

indices = [0, 2, 4]
print("Selected elements:", arr[indices])

arr2d = np.array([[10, 20], [30, 40], [50, 60]])
print("Row selection:", arr2d[[0, 2]])   # Select rows 0 and 2


Selected elements: [10 30 50]
Row selection: [[10 20]
 [50 60]]



---


## Boolean Indexing

You can filter elements using boolean conditions.

In [7]:
arr = np.array([5, 10, 15, 20, 25])

# Condition
print(arr > 12)

# Filtering
print("Elements > 12:", arr[arr > 12])

# Even numbers only
print("Even numbers:", arr[arr % 2 == 0])


[False False  True  True  True]
Elements > 12: [15 20 25]
Even numbers: [10 20]



---


## Practical Example


In [8]:

data = np.array([12, 7, 5, 22, 19, 30, 41, 55, 2])

# Find elements greater than 20
print("Numbers > 20:", data[data > 20])

# Get even numbers only
print("Even Numbers:", data[data % 2 == 0])

# Select specific indices
print("Pick 1st, 4th, 7th element:", data[[0, 3, 6]])


Numbers > 20: [22 30 41 55]
Even Numbers: [12 22 30  2]
Pick 1st, 4th, 7th element: [12 22 41]



---

## Summary

In this notebook, we learned:

- **Attributes of NumPy arrays**:
  - `.ndim` → number of dimensions  
  - `.shape` → size of each dimension  
  - `.size` → total number of elements  
  - `.dtype` → data type of elements  

- **Indexing in NumPy arrays**:
  - Similar to Python lists (0-based indexing).
  - Supports **negative indexing** for accessing elements from the end.
  - Works with 1D, 2D, and higher-dimensional arrays.

- **Slicing arrays**:
  - `array[start:end]` → extracts a portion.
  - `array[start:end:step]` → with step size.
  - Supports slicing across multiple dimensions.

- **Multidimensional indexing**:
  - Use commas: `array[row, col]`
  - Can extract specific rows, columns, or submatrices.

✅ With attributes and indexing, you can now **understand your arrays better and manipulate their contents efficiently**, which is the foundation for most NumPy operations.

---
