# 04 - Array Operations in NumPy
**`04-array-operations.ipynb`**

In this notebook, we will learn about **array operations in NumPy**, which make it extremely powerful for numerical computing. Unlike Python lists, NumPy arrays allow **element-wise operations**, broadcasting, and efficient mathematical computations.

---


## 1. Arithmetic Operations

NumPy allows **element-wise arithmetic** operations directly on arrays.


In [1]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", b / a)
print("Power:", a ** 2)


Addition: [11 22 33 44]
Subtraction: [ -9 -18 -27 -36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]
Power: [ 1  4  9 16]



---


## 2. Universal Functions (ufuncs)

NumPy provides **built-in mathematical functions** (called *ufuncs*) that operate element-wise on arrays.

In [7]:

arr = np.array([1, 4, 9, 16])

print("Square root:", np.sqrt(arr))
print("Exponential:", np.exp(arr))
print("Logarithm:", np.log(arr))
print("Sine:", np.sin(arr))
print("Cosine:", np.cos(arr))


Square root: [1. 2. 3. 4.]
Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
Logarithm: [0.         1.38629436 2.19722458 2.77258872]
Sine: [ 0.84147098 -0.7568025   0.41211849 -0.28790332]
Cosine: [ 0.54030231 -0.65364362 -0.91113026 -0.95765948]


👉 Ufuncs are **vectorized**, meaning they work faster than looping through elements in Python.

---

## 3. Aggregate Functions

NumPy arrays support **aggregation** (finding overall values like sum, mean, etc.).

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))
print("Standard Deviation:", np.std(arr))
print("Variance:", np.var(arr))

Sum: 21
Mean: 3.5
Max: 6
Min: 1
Standard Deviation: 1.707825127659933
Variance: 2.9166666666666665


👉 Aggregations can also be done **across axes** for multidimensional arrays.


In [8]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

print("Sum of all elements:", np.sum(matrix))
print("Sum across rows:", np.sum(matrix, axis=1))
print("Sum across columns:", np.sum(matrix, axis=0))


Sum of all elements: 21
Sum across rows: [ 6 15]
Sum across columns: [5 7 9]



---


## 4. Broadcasting

Broadcasting allows NumPy to perform operations on arrays of **different shapes**.


In [3]:
a = np.array([1, 2, 3])
b = 2  # Scalar

print("Array + Scalar:", a + b)


Array + Scalar: [3 4 5]


In [4]:
# Broadcasting with 2D array
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
vector = np.array([10, 20, 30])

print("Matrix + Vector:\n", matrix + vector)

Matrix + Vector:
 [[11 22 33]
 [14 25 36]]


👉 Broadcasting rules:

1. If arrays have different dimensions, NumPy pads with ones.
2. Sizes must match or one must be `1`.

---

## 5. Comparison Operations

NumPy supports element-wise comparisons.

In [5]:
arr = np.array([1, 2, 3, 4, 5])

print("Greater than 2:", arr > 2)
print("Equal to 3:", arr == 3)

# Boolean indexing
print("Elements greater than 2:", arr[arr > 2])

Greater than 2: [False False  True  True  True]
Equal to 3: [False False  True False False]
Elements greater than 2: [3 4 5]



---


## 6. Linear Algebra Operations

NumPy includes functions for **matrix operations**.

In [6]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("Matrix Multiplication:\n", np.dot(A, B))
print("Transpose:\n", A.T)
print("Determinant:", np.linalg.det(A))
print("Inverse:\n", np.linalg.inv(A))


Matrix Multiplication:
 [[19 22]
 [43 50]]
Transpose:
 [[1 3]
 [2 4]]
Determinant: -2.0000000000000004
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]



---


## Summary

In this notebook, we learned about:

* **Arithmetic operations** (element-wise addition, subtraction, etc.)
* **Universal functions (ufuncs)** like `sqrt`, `exp`, `log`, `sin`, etc.
* **Aggregate functions** like `sum`, `mean`, `std`, etc.
* **Broadcasting** → operations on arrays of different shapes.
* **Comparison operations** with boolean indexing.
* **Linear algebra operations** like dot product, transpose, determinant, and inverse.

✅ NumPy makes mathematical operations **fast and concise**, forming the basis for scientific and data-intensive applications.

---



---
