# 05 – Array Manipulation in NumPy
**`05-array-manipulation.ipynb`**

In this notebook, we will explore different ways to manipulate arrays in NumPy.
Array manipulation is an essential part of numerical computing, allowing us to reshape, join, or split arrays as needed.

---



## Topics Covered

* Reshaping Arrays
* Flattening Arrays
* Transposing Arrays
* Stacking Arrays
* Splitting Arrays

---


## Reshaping Arrays

We can change the shape of an array without changing its data using the `reshape()` method.


In [1]:
import numpy as np

# Original array
arr = np.arange(12)
print("Original Array:", arr)

# Reshape into 3x4
reshaped = arr.reshape(3, 4)
print("\nReshaped (3x4):\n", reshaped)

# Reshape into 2x2x3
reshaped_3d = arr.reshape(2, 2, 3)
print("\nReshaped (2x2x3):\n", reshaped_3d)


Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped (2x2x3):
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


🔹 Note: The product of dimensions must match the number of elements.

---

## Flattening Arrays

Convert a multi-dimensional array into a 1D array.


In [2]:
# Flatten using flatten()
flat1 = reshaped.flatten()
print("Flattened with flatten():", flat1)

# Flatten using ravel()
flat2 = reshaped.ravel()
print("Flattened with ravel():", flat2)


Flattened with flatten(): [ 0  1  2  3  4  5  6  7  8  9 10 11]
Flattened with ravel(): [ 0  1  2  3  4  5  6  7  8  9 10 11]


🔹 `flatten()` returns a copy,
🔹 `ravel()` returns a view (changes affect original array).

---

## Transposing Arrays

Transpose rearranges axes (like flipping rows and columns).


In [3]:
# Transpose of a 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Original:\n", arr2d)
print("Transposed:\n", arr2d.T)

# Transpose of a 3D array
arr3d = np.arange(24).reshape(2, 3, 4)
print("\nOriginal 3D shape:", arr3d.shape)
print("Transposed (swap axes):", arr3d.transpose(1, 0, 2).shape)


Original:
 [[1 2 3]
 [4 5 6]]
Transposed:
 [[1 4]
 [2 5]
 [3 6]]

Original 3D shape: (2, 3, 4)
Transposed (swap axes): (3, 2, 4)



---



## Stacking Arrays

We can **combine multiple arrays** vertically, horizontally, or depth-wise.



In [4]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Vertical stacking (row-wise)
vstacked = np.vstack((a, b))
print("Vertical Stack:\n", vstacked)

# Horizontal stacking (column-wise)
hstacked = np.hstack((a, b))
print("\nHorizontal Stack:\n", hstacked)

# Depth stacking (along new axis)
dstacked = np.dstack((a, b))
print("\nDepth Stack:\n", dstacked)


Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]

Depth Stack:
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]



---



## Splitting Arrays

We can split arrays into multiple smaller arrays.


In [5]:
arr = np.arange(12).reshape(3, 4)
print("Original Array:\n", arr)

# Split into 2 equal parts horizontally
hsplit = np.hsplit(arr, 2)
print("\nHorizontal Split:")
for part in hsplit:
    print(part)

# Split into 3 equal parts vertically
vsplit = np.vsplit(arr, 3)
print("\nVertical Split:")
for part in vsplit:
    print(part)


Original Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Horizontal Split:
[[0 1]
 [4 5]
 [8 9]]
[[ 2  3]
 [ 6  7]
 [10 11]]

Vertical Split:
[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]



---



## Summary

In this notebook, we covered:

* **Reshaping** arrays to different dimensions
* **Flattening** arrays into 1D
* **Transposing** arrays (2D and 3D)
* **Stacking** arrays vertically, horizontally, and depth-wise
* **Splitting** arrays into smaller parts

---



👉 Next, we’ll move to **`06-mathematical-functions.ipynb`**, where we will explore mathematical and statistical functions in NumPy.

---
