# 07-random-module.ipynb
**`07-random-module.ipynb`**

# NumPy Random Module

In this notebook, we will learn about **NumPy's `random` module**, which provides powerful tools for generating random numbers, simulating probability distributions, and performing random sampling.

---



## Topics Covered
- Introduction to NumPy Random
- Generating Random Numbers
- Random Sampling
- Random Integers
- Probability Distributions
  - Uniform Distribution
  - Normal (Gaussian) Distribution
  - Binomial Distribution
- Shuffling and Permutations
- Practical Examples
- Summary

---


## Introduction to NumPy Random

The `numpy.random` module allows us to generate:
- Random integers
- Random floats
- Random samples from distributions
- Randomly shuffled arrays

This is widely used in:
- Data Science (train-test splitting, bootstrapping)
- Machine Learning (weight initialization, data augmentation)
- Simulations and Modeling

---


In [1]:
import numpy as np


---

## Generating Random Numbers
We can generate random numbers using:

- `np.random.rand()` → random floats in range `[0, 1)`.
- `np.random.randn()` → random floats from standard normal distribution.
- `np.random.random()` → another way to get random floats `[0, 1)`.


In [2]:
# Random floats between 0 and 1
print("rand:", np.random.rand(3))

# Random floats from normal distribution
print("randn:", np.random.randn(3))

# Another way to generate random floats [0, 1)
print("random:", np.random.random(3))


rand: [0.71059666 0.75846493 0.38901202]
randn: [-1.50708351  1.8689838  -0.28229912]
random: [0.35485032 0.51366994 0.71490808]



---


## Random Sampling
We can randomly select values from arrays.


In [3]:
arr = np.array([10, 20, 30, 40, 50])
print("Original array:", arr)

# Random choice from array
print("Random choice:", np.random.choice(arr, 3))


Original array: [10 20 30 40 50]
Random choice: [20 20 30]



---

## Random Integers
We can generate random integers using `np.random.randint(low, high, size)`.
```


In [4]:
# Random integers between 1 and 10
print(np.random.randint(1, 10, 5))


[1 6 1 4 1]


---

## Probability Distributions

NumPy provides functions to simulate various probability distributions.

### 1. Uniform Distribution
Numbers are drawn from a uniform distribution over `[low, high)`.

In [5]:
# Uniform distribution
print(np.random.uniform(1, 5, 5))


[1.04910018 2.10244874 2.71854896 4.14950798 2.50757521]



---



### 2. Normal (Gaussian) Distribution
Numbers are drawn from a normal distribution with `mean` and `standard deviation`.


In [6]:
# Normal distribution with mean=0, std=1
print(np.random.normal(0, 1, 5))

# Normal distribution with mean=10, std=2
print(np.random.normal(10, 2, 5))


[-1.8179795  -0.56581526  0.62823586 -1.13824604 -1.97658364]
[ 7.13879846  9.83347326 11.71619979  8.78700953 12.23519536]



---


### 3. Binomial Distribution
Useful in probability & statistics — simulates number of successes in `n` trials.
```


In [7]:
# Binomial distribution: 10 trials, prob of success=0.5, size=5
print(np.random.binomial(10, 0.5, 5))


[6 5 5 3 3]



---


## Shuffling and Permutations

We can shuffle arrays randomly or generate random permutations.


In [8]:
arr = np.arange(10)
print("Before shuffle:", arr)

np.random.shuffle(arr)
print("After shuffle:", arr)

print("Random permutation:", np.random.permutation(10))


Before shuffle: [0 1 2 3 4 5 6 7 8 9]
After shuffle: [8 9 6 1 7 3 4 5 2 0]
Random permutation: [5 1 2 3 0 9 6 8 4 7]



---



## Practical Examples

1. **Simulating a Dice Roll**


In [9]:
# Dice roll (1 to 6)
dice_rolls = np.random.randint(1, 7, 10)
print("10 dice rolls:", dice_rolls)

10 dice rolls: [4 4 5 3 4 2 1 5 3 2]



---

2. **Train-Test Split (Random Sampling)**



In [10]:
data = np.arange(1, 21)
print("Data:", data)

# Randomly selecting 70% for training
train = np.random.choice(data, size=14, replace=False)
test = np.setdiff1d(data, train)

print("Train data:", train)
print("Test data:", test)


Data: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Train data: [ 5  2 11  1 17 20  4  7 15  8 13  6 14 12]
Test data: [ 3  9 10 16 18 19]



---


3. **Monte Carlo Simulation Example**

Estimate the value of π (pi) using random sampling.


In [11]:
N = 100000
x = np.random.rand(N)
y = np.random.rand(N)

# Points inside circle: x^2 + y^2 <= 1
inside_circle = np.sum(x**2 + y**2 <= 1)

pi_estimate = (inside_circle / N) * 4
print("Estimated π:", pi_estimate)


Estimated π: 3.14392



---


## Summary

- `np.random.rand(), np.random.randn(), np.random.random()` → generate random numbers.
- `np.random.randint()` → random integers.
- `np.random.choice()` → random sampling.
- Distributions:
  - **Uniform:** `np.random.uniform(low, high, size)`
  - **Normal:** `np.random.normal(mean, std, size)`
  - **Binomial:** `np.random.binomial(n, p, size)`
- `np.random.shuffle()` and `np.random.permutation()` → shuffle data.
- Applications: data splitting, simulations, ML initialization, Monte Carlo methods.

NumPy's `random` module is essential for **probability, statistics, and machine learning workflows**.

---

